

[[redirects]]
  from = "/placeholder-images/sitemap.xml"
  to = "https://placeholderimages.netlify.app/sitemap.xml"
  force = true
  status = 200

[[redirects]]
  from = "/placeholder-image-generator-tools"
  to = "https://placeholderimages.netlify.app/placeholder-image-generator-tools"
  force = true
  status = 200	
  
 [[redirects]]
  from = "/placeholder-images"
  to = "https://placeholderimages.netlify.app/placeholder-images"
  force = true
  status = 200

[[redirects]]
  from = "/placeholder-images*"
  to = "https://placeholderimages.netlify.app/placeholder-images/:splat"
  force = true
  status = 200
  
  
[[redirects]]
  from = "/conv/sitemap.xml"
  to = "https://safeimagekitconv.netlify.app/sitemap.xml"
  force = true
  status = 200

[[redirects]]
  from = "/conv"
  to = "https://safeimagekitconv.netlify.app"
  force = true
  status = 200

[[redirects]]
  from = "/conv*"
  to = "https://safeimagekitconv.netlify.app/conv/:splat"
  force = true
  status = 200

  [[redirects]]
  from = "/twitter"
  to = "https://safeimagekit-twitter.netlify.app/"
  force = true
  status = 200
  
  [[redirects]]
  from = "/twitter/sitemap.xml"
  to = "https://safeimagekit-twitter.netlify.app/sitemap.xml"
  force = true
  status = 200

[[redirects]]
  from = "/twitter/*"
  to = "https://safeimagekit-twitter.netlify.app/twitter/:splat"
  force = true
  status = 200

[[redirects]]
  from = "/instagram"
  to = "https://safeimagekit-instagram.netlify.app/"
  force = true
  status = 200

[[redirects]]
  from = "/instagram/sitemap.xml"
  to = "https://safeimagekit-instagram.netlify.app/sitemap.xml"
  force = true
  status = 200

[[redirects]]
  from = "/instagram/*"
  to = "https://safeimagekit-instagram.netlify.app/instagram/:splat"
  force = true
  status = 200

[[redirects]]
  from = "/discord"
  to = "https://safeimagekit-discord.netlify.app/"
  force = true
  status = 200

[[redirects]]
  from = "/discord/sitemap.xml"
  to = "https://safeimagekit-discord.netlify.app/sitemap.xml"
  force = true
  status = 200

[[redirects]]
  from = "/discord/*"
  to = "https://safeimagekit-discord.netlify.app/discord/:splat"
  force = true
  status = 200

  [[redirects]]
  from = "/linkedin"
  to = "https://safeimagekit-linkedin.netlify.app/"
  force = true
  status = 200

[[redirects]]
  from = "/linkedin/sitemap.xml"
  to = "https://safeimagekit-linkedin.netlify.app/sitemap.xml"
  force = true
  status = 200

[[redirects]]
  from = "/linkedin/*"
  to = "https://safeimagekit-linkedin.netlify.app/linkedin/:splat"
  force = true
  status = 200

  [[redirects]]
  from = "/facebook"
  to = "https://safeimagekit-facebook.netlify.app/"
  force = true
  status = 200

[[redirects]]
  from = "/facebook/sitemap.xml"
  to = "https://safeimagekit-facebook.netlify.app/sitemap.xml"
  force = true
  status = 200

[[redirects]]
  from = "/facebook/*"
  to = "https://safeimagekit-facebook.netlify.app/facebook/:splat"
  force = true
  status = 200


[[redirects]]
  from = "/youtube"
  to = "https://safeimagekit-youtube.netlify.app/"
  force = true
  status = 200

[[redirects]]
  from = "/youtube/sitemap.xml"
  to = "https://safeimagekit-youtube.netlify.app/sitemap.xml"
  force = true
  status = 200

[[redirects]]
  from = "/youtube/*"
  to = "https://safeimagekit-youtube.netlify.app/youtube/:splat"
  force = true
  status = 200
  
 [[redirects]]
  from = "/ppm"
  to = "https://safeimagekit-ppm.netlify.app"
  force = true
  status = 200

[[redirects]]
  from = "/ppm/sitemap.xml"
  to = "https://safeimagekit-ppm.netlify.app/sitemap.xml"
  force = true
  status = 200

[[redirects]]
  from = "/ppm/*"
  to = "https://safeimagekit-ppm.netlify.app/ppm/:splat"
  force = true
  status = 200
  
[[redirects]]
  from = "/adjust/sitemap.xml"
  to = "https://safeimagekit-adjust.netlify.app/sitemap.xml"
  force = true
  status = 200

[[redirects]]
  from = "/adjust"
  to = "https://safeimagekit-adjust.netlify.app/"
  force = true
  status = 200

[[redirects]]
  from = "/adjust*"
  to = "https://safeimagekit-adjust.netlify.app/adjust/:splat"
  force = true
  status = 200


[[redirects]]
  from = "/draw/sitemap.xml"
  to = "https://safeimagekit-draw.netlify.app/sitemap.xml"
  force = true
  status = 200

[[redirects]]
  from = "/draw"
  to = "https://safeimagekit-draw.netlify.app/"
  force = true
  status = 200

[[redirects]]
  from = "/draw*"
  to = "https://safeimagekit-draw.netlify.app/draw/:splat"
  force = true
  status = 200





[[redirects]]
  from = "/base64/sitemap.xml"
  to = "https://safeimagekit-base64.netlify.app/sitemap.xml"
  force = true
  status = 200

[[redirects]]
  from = "/base64"
  to = "https://safeimagekit-base64.netlify.app/"
  force = true
  status = 200

[[redirects]]
  from = "/base64*"
  to = "https://safeimagekit-base64.netlify.app/base64/:splat"
  force = true
  status = 200


[[redirects]]
  from = "/png/sitemap.xml"
  to = "https://safeimagekit-png.netlify.app/sitemap.xml"
  force = true
  status = 200

[[redirects]]
  from = "/png"
  to = "https://safeimagekit-png.netlify.app/"
  force = true
  status = 200

[[redirects]]
  from = "/png/*"
  to = "https://safeimagekit-png.netlify.app/png/:splat"
  force = true
  status = 200
 
  [[redirects]]
  from = "/gif/sitemap.xml"
  to = "https://safeimagekit-giftools.netlify.app/sitemap.xml"
  force = true
  status = 200

[[redirects]]
  from = "/gif"
  to = "https://safeimagekit-giftools.netlify.app/"
  force = false
  status = 200

[[redirects]]
  from = "/gif/*"
  to = "https://safeimagekit-giftools.netlify.app/gif/:splat"
  force = false
  status = 200
  
[[redirects]]
  from = "/filter/sitemap.xml"
  to = "https://safeimagekit-filters.netlify.app/sitemap.xml"
  force = true
  status = 200

[[redirects]]
  from = "/filter"
  to = "https://safeimagekit-filters.netlify.app/"
  force = true
  status = 200

[[redirects]]
  from = "/filter*"
  to = "https://safeimagekit-filters.netlify.app/filter/:splat"
  force = true
  status = 200

[[redirects]]
  from = "/border/sitemap.xml"
  to = "https://safeimagekit-border.netlify.app/sitemap.xml"
  force = true
  status = 200

[[redirects]]
  from = "/border"
  to = "https://safeimagekit-border.netlify.app/"
  force = true
  status = 200

[[redirects]]
  from = "/border*"
  to = "https://safeimagekit-border.netlify.app/border/:splat"
  force = true
  status = 200

[[redirects]]
  from = "/jpg/sitemap.xml"
  to = "https://safeimagekit-jpg.netlify.app/sitemap.xml"
  force = true
  status = 200

[[redirects]]
  from = "/jpg/"
  to = "https://safeimagekit-jpg.netlify.app/"
  force = true
  status = 200

[[redirects]]
  from = "/jpg/*"
  to = "https://safeimagekit-jpg.netlify.app/jpg/:splat"
  force = true
  status = 200

[[redirects]]
  from = "/effects/sitemap.xml"
  to = "https://safeimagekit-effects.netlify.app/sitemap.xml"
  force = true
  status = 200

[[redirects]]
  from = "/effects/"
  to = "https://safeimagekit-effects.netlify.app/"
  force = true
  status = 200

[[redirects]]
  from = "/effects*"
  to = "https://safeimagekit-effects.netlify.app/effects/:splat"
  force = true
  status = 200
  
  [[redirects]]
  from = "/charts/sitemap.xml"
  to = "https://safeimagekit-charts.netlify.app/sitemap.xml"
  force = true
  status = 200

[[redirects]]
  from = "/charts"
  to = "https://safeimagekit-charts.netlify.app/"
  force = true
  status = 200

[[redirects]]
  from = "/charts*"
  to = "https://safeimagekit-charts.netlify.app/charts/:splat"
  force = true
  status = 200

  
[[redirects]]
  from = "/models/*"
  to = "https://safeimagekit-effects.netlify.app/models/:splat"
  force = true
  status = 200
[build]
  functions="build"